Leezekun/MassGen

docs/case_studies/collaborative_creative_writing.md
docs/case_studies/diverse_ai_news.md
docs/case_studies/grok_hle_cost.md
docs/case_studies/imo_2025_winner.md
docs/case_studies/stockholm_travel_guide.md

Add some text so that it is clear that the image is clickable and it leads to the recorded case study:

Add text for the case study videos

---

README.md

This PR adds a visible **Discord banner** to the `README.md`, enabling users and contributors to easily join the MassGen community.
-  **Added Discord banner** linking to: [https://discord.gg/VVrT2rQaz5](https://discord.gg/VVrT2rQaz5)
-  Centered the project logo for better visual structure
-  Rearranged banners (Python, License, Discord) in a horizontal and aligned format using HTML
-  Centered the demo video thumbnail for improved readability
<p align="center">
<a href="https://www.python.org/downloads/">
</a>
<a href="LICENSE">
</a>
<a href="https://discord.gg/VVrT2rQaz5">
</a>
</p>
---
Let me know if you’d like me to adjust banner style, add more links, or format any other sections!

Docs: Update README by Improving Presentation with Discord Banner

---

examples/demo_phase2.py
massgen/v2/__init__.py
massgen/v2/message_templates.py
massgen/v2/orchestrator.py

Creating a PR to the dev branch for incremental review.
Summary
Implements the complete MassGen v0.0.2 orchestrator architecture with ChatAgent interface, real-time streaming coordination, comprehensive logging, and flexible voting configuration.
Major Components Added
🏗️ Core v0.0.2 Architecture
- ChatAgent abstract base class for unified agent interface
- StreamChunk standardized streaming response format
- AgentBackend unified backend system with token tracking
- SimpleAgent full-featured agent implementation with streaming
- Factory functions for easy agent creation (create_simple_agent, create_agent_team)
🎯 MASS Orchestrator Implementation
- Complete MASS binary decision framework (vote OR new_answer)
- Anonymous agent coordination (agent1, agent2, etc.) to reduce bias
- Real-time …

Phase 2 of Epic #16: Orchestrator

---

massgen/__init__.py

Change the version number from 1.0.0 to 0.0.1

Change version number to 0.0.1

---

docs/case_studies/imo_2025_winner.md

Remove IMO video as it was not recorded using 0.0.1alpha version of code. We will focus on 0.0.3 code for now and directly record use cases for 0.0.3.

Remove imo video

---

README.md
docs/case_studies/berkeley-conference-talks.md
docs/case_studies/collaborative_creative_writing.md
docs/case_studies/diverse_ai_news.md
docs/case_studies/grok_hle_cost.md
docs/case_studies/imo_2025_winner.md
docs/case_studies/odsc-conference-talks.md
docs/case_studies/stockholm_travel_guide.md
docs/presentation/berkeley.html

remove unnecessary steps and use `uv run`

simplify setup

---

massgen/configs/gemini_4o_claude.yaml

Fix issue: https://github.com/Leezekun/MassGen/issues/51

Fix claude config

---

docs/case_studies/diverse_ai_news.md

Currently the AI news case summary is not accurate.

Fix AI-news case

---

massgen/backend/claude_code.py
massgen/chat_agent.py
massgen/configs/claude_code_single.yaml
massgen/configs/single_flash2.5.yaml
massgen/message_templates.py

creating a PR for incremental merge.

cleanup and todo

---

.env.example
README.md
massgen/agent_config.py
massgen/backend/chat_completions.py
massgen/cli.py
massgen/configs/zai_coding_team.yaml
massgen/configs/zai_glm45.yaml
massgen/utils.py

This pull request adds first-class support for the Z AI (GLM-4.5) model provider to the project. It introduces new configuration options, updates documentation, and implements backend logic to enable seamless integration with Z AI's OpenAI-compatible API. Example configuration files for Z AI agents and teams are also included.
**Z AI (GLM-4.5) integration:**
* Added Z AI API key support in `.env.example` and documented usage in `README.md`, including setup instructions and links to Z AI documentation. [[1]](diffhunk://#diff-a3046da0d15a27e89f2afe639b25748a7ad4d9290af3e7b1b6c1a5533c8f0a8cR10-R12) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R201) [[3]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R212-R218)
* …

Add GLM-4.5 support

---

massgen/backend/chat_completions.py
massgen/frontend/coordination_ui.py
massgen/frontend/displays/base_display.py
massgen/frontend/displays/rich_terminal_display.py

Test:
```bash
uv run python -m massgen.cli --backend zai --model glm-4.5 --base-url https://api.z.ai/api/paas/v4 "2+2=?"
```

Present reasoning start and completion for GLM

---

.env.example

This is an emergency patch post v0.0.7 release

comment a line in .env.example

---

README.md
docs/presentation/datahack_summit_2025.html

- **slides update**
- **address feedback**
- **gpt-5 challenge update**
- **example update**

v0.0.9 presentation update

---

docs/case_studies/neurips_2025_website_collaboration.md
massgen/backend/claude_code.py
massgen/orchestrator.py

Store claude code files in the `massgen_logs` folder with time stamp

add logs for claude code files

---

CONTRIBUTING.md

Update Project Structure in CONTRIBUTING.md

Update Project Structure in CONTRIBUTING.md

---

.github/pull_request_template.md
.github/workflows/pr-title-check.yml
.github/workflows/pre-commit.yml
.pre-commit-config.yaml
CONTRIBUTING.md
MANIFEST.in
pull_request_template.md
pyproject.toml

This PR introduces automated code quality checks through pre-commit hooks and GitHub Actions workflows. It sets up pre-commit configuration for Python code formatting, linting, and validation, along with automated PR title validation to ensure consistent commit message formatting. The PR also enhances the contributing guide with detailed development workflow instructions and moves the PR template to the proper GitHub location.
```
```
- Added .pre-commit-config.yaml with comprehensive Python code quality checks (ruff, mypy, black, isort, etc.)
- Created GitHub Actions workflow for running pre-commit checks on PRs
- Added PR title validation workflow to enforce conventional commit format
- Moved and enhanced PR template to .github/pull_request_template.md with clear formatting guidelines
- …

ci: add precommit check

---

CHANGELOG.md
CONTRIBUTING.md
README.md
ROADMAP_v0.0.24.md
docs/case_studies/SuperIntelligence.md
docs/case_studies/berkeley-conference-talks.md
docs/case_studies/collaborative_creative_writing.md
docs/case_studies/diverse_ai_news.md
docs/case_studies/fibonacci_number_algorithms.md
docs/case_studies/gemini-mcp-notion-integration.md
docs/case_studies/grok_hle_cost.md
docs/case_studies/imo_2025_winner.md
docs/case_studies/stockholm_travel_guide.md
massgen/configs/README.md

Valid types:
Examples:
```
```

docs: Update docs for v0.0.23

---

.github/workflows/auto-release.yml

Valid types:
Examples:
```
```

ci: update auto release

---

massgen/backend/utils/filesystem_manager/_filesystem_manager.py
massgen/cli.py
massgen/configs/tools/filesystem/multiturn/grok4_gpt5_gemini_filesystem_multiturn.yaml
massgen/configs/tools/filesystem/multiturn/two_gemini_flash_filesystem_multiturn.yaml
massgen/mcp_tools/client.py
massgen/orchestrator.py
massgen/tests/test_path_permission_manager.py

Valid types:
Examples:
```
```

Fix import problem & update configs

---

CHANGELOG.md
CONTRIBUTING.md
README.md
ROADMAP_v0.0.27.md
massgen/__init__.py

Valid types:
Examples:
```
```

docs: docs for v0.0.26

---

docs/presentation/components/slide-call-to-action.html
docs/presentation/components/slide-evolution-from-v001.html

Valid types:
Examples:
```
```

docs: version update post v0.0.26

---

.github/pull_request_template.md

Added sections for testing instructions and expected results in the pull request template.
Valid types:
Examples:
```
```

ci: Enhance pull request template with testing details

---

docs/presentation/applied-ai-summit.html
docs/presentation/components/slide-call-to-action.html
docs/presentation/components/slide-evolution-from-v001.html
docs/presentation/components/slide-getting-started.html

Valid types:
Examples:
Updated evolution, call for action and getting started pages.
Are there new case studies that we should use to replace some current ones? Will there be before Oct 10?
```
```
Add test method for this PR.
Write down …

docs: update presentation post v0.0.28
